// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOu8VlufjV4tbQRKR9h1SXD_hCIgzNdQ8',
    appId: '1:243961147976:web:3d52be5ece29869cb01e7d',
    messagingSenderId: '243961147976',
    projectId: 'couplediaryapp-fb3c8',
    authDomain: 'couplediaryapp-fb3c8.firebaseapp.com',
    storageBucket: 'couplediaryapp-fb3c8.appspot.com',
    measurementId: 'G-3NG202Y3SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVRvs4XeHhhlUHLgcrI6o2smdbIBvoIHE',
    appId: '1:243961147976:android:ad755b9a71bb22a6b01e7d',
    messagingSenderId: '243961147976',
    projectId: 'couplediaryapp-fb3c8',
    storageBucket: 'couplediaryapp-fb3c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBovPbXxFTsj9PYZwW_-y0UAaS6XqEF2-0',
    appId: '1:243961147976:ios:39552596de9b0ad6b01e7d',
    messagingSenderId: '243961147976',
    projectId: 'couplediaryapp-fb3c8',
    storageBucket: 'couplediaryapp-fb3c8.appspot.com',
    iosClientId: '243961147976-7oalmmlipuetdk6vbdaqrp6njr4us7ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyerimcoupleqna230317',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBovPbXxFTsj9PYZwW_-y0UAaS6XqEF2-0',
    appId: '1:243961147976:ios:45b791d81ac3cbecb01e7d',
    messagingSenderId: '243961147976',
    projectId: 'couplediaryapp-fb3c8',
    storageBucket: 'couplediaryapp-fb3c8.appspot.com',
    iosClientId: '243961147976-3ppkullo5pp34qbmpqdba6vrs1jb1sqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupleDiaryApp',
  );
}
